import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/navBar";
import SideBar from "@/components/SideBar/sideBar";
import RightBar from "@/components/RightBar/rightBar";
import Footer from "@/components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className=" h-[180vh]">
          <SideBar />
        <RightBar />
        {children}

        </main>
        <Footer />
        </body>
    </html>
  );
}
